name: Maven Build and Dockerize

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: docker build -t taxservice:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-image-name:latest ${{ secrets.DOCKER_USER }}/taxservice:latest
          docker push ${{ secrets.DOCKER_USER }}/taxservice:latest
